name: gpt
description: A command line tool for running GPT commands. This tool supports prompt-batching and prompt-chaining.
version: 0.9.1
repository: https://github.com/sisbell/stackwire-gpt
issue_tracker: https://github.com/sisbell/stackwire-gpt/issues
executables:
  air:
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.18.7 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mockito: ^5.4.0
dependencies:
  archive: ^3.3.7
  args: ^2.4.0
  http: ^0.13.5
  interact: ^2.2.0
  path: ^1.8.3
  yaml: ^3.1.1
