name: eom
description: A command line app for testing of OpenAI APIs.
version: 0.1.0

environment:
  sdk: '>=2.18.7 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
  universal_io: ^2.2.0
