---
projectName: experiment-chain-multiple
projectVersion: '1.7'
apiKeyFile: "../../api_key"
blocks:
  - blockId: chain-1
    pluginName: ExperimentGptPlugin
    blockRuns: 2
    configuration:
      requestParams:
        model: gpt-3.5-turbo
        temperature: 1.2
        top_p: 1
        max_tokens: 500
    executions:
      - id: exp-1
        chainRuns: 2
        promptChain:
          - structured-story.prompt
          - character-action.prompt
        excludesMessageHistory:
          - character-action.prompt
        fixJson: true
        responseFormat: json
        properties:
          rank: Commander in Starfleet
          show: Star Trek
          mainCharacterName: ''
          story: ''
          characterAction: ''

  # Block demonstrates the use of importing properties
  - blockId: chain-2
    pluginName: ExperimentGptPlugin
    configuration:
      requestParams:
        model: gpt-3.5-turbo
        temperature: 1.2
        top_p: 1
        max_tokens: 500
    executions:
      - id: exp-2-import
        chainRuns: 2
        promptChain:
          - structured-story.prompt
          - character-action.prompt
        excludesMessageHistory:
          - character-action.prompt
        fixJson: true
        responseFormat: json
        properties:
          rank: Commander in Starfleet
          mainCharacterName: ''
          story: ''
          characterAction: ''
        # Import properties from a properties file
        import:
          propertiesFile: properties.json
          properties:
            rank: 3
            show: 2

  - blockId: report-1
    pluginName: ReportingGptPlugin
    executions:
      - id: report-1
        blockIds:
          - chain-1
          - chain-2