---
projectName: experiment-reporting
projectVersion: '1.7'
apiKeyFile: "../../api_key"
blocks:
  - blockId: chain-1
    pluginName: ExperimentGptPlugin
    blockRuns: 1
    configuration:
      requestParams:
        model: gpt-3.5-turbo
        temperature: 1.2
        top_p: 1
        max_tokens: 500
    executions:
      - id: exp-1
        chainRuns: 2
        promptChain:
          - structured-story.prompt
          - character-action.prompt
        excludesMessageHistory:
          - character-action.prompt
        fixJson: true
        responseFormat: json
        properties:
          rank: Commander in Starfleet
          show: Star Trek
          mainCharacterName: ''
          story: ''
          characterAction: ''
    # Generate HTML Report
  - blockId: report-1
    pluginName: ReportingGptPlugin
    executions:
      - id: report-execution
        blockIds:
          - chain-1