---
projectName: "${projectName}"
projectVersion: "${projectVersion}"
apiKeyFile: "${apiKeyFile}"
blocks:
  - blockId: batch-1
    pluginName: BatchGptPlugin
    blockRuns: ${blockRuns}
    configuration:
      requestParams:
        model: gpt-3.5-turbo
        temperature: 0.7
        top_p: 1
        max_tokens: 500
    executions:
      - id: batch-1
        dataFile: batch-data.json
        prompt: batch.prompt